environment                   = "prd"
location-prd                  = "westeurope"
resourcegroupname-prd         = "vnet-prod-rg"
vnetname-prd                  = "vnet-prod-01"
vnetaddressspaceprd           = "10.68.0.0/16"
subnetname-prd                = "sub-01"
subnetaddressspace-prd        = "10.68.1.0/24"
networkinterfacename-prd      = "nic-01"
nsgname-prd                   = "nsg-prod-01"
publicipname-prd              = "pip-01"

