increment                     = "002"
environment                   = "dev"
vnetaddressspace              = "10.0.0.0/16"
subnetaddressspace            = "10.0.1.0/24"
location                      = "westeurope"
