environment                   = "prod"
vnetaddressspace              = "10.68.0.0/16"
subnetaddressspace            = "30.68.1.0/24"
location                      = "westeurope"
storageaccounttier            = "Standard"
storageaccountreplicationtype = "GRS"